modify /etc/init.d/control-port-filter-python

diff --git a/etc/init.d/control-port-filter-python b/etc/init.d/control-port-filter-python
--- a/etc/init.d/control-port-filter-python
+++ b/etc/init.d/control-port-filter-python
@@ -22,8 +22,9 @@
 PATH=/sbin:/usr/sbin:/bin:/usr/bin
 DESC="Control Port Filter Proxy"
 NAME=control-port-filter-python
-DAEMON=/usr/lib/control-port-filter-python/cpfp.py
-DAEMON_ARGS=""
+#DAEMON=/usr/lib/control-port-filter-python/cpfp.py
+DAEMON=/usr/sbin/cpfpd
+DAEMON_ARGS="start stop restart"
 PIDFILE=/var/run/$NAME/pid
 SCRIPTNAME=/etc/init.d/$NAME
 
@@ -51,7 +52,7 @@ chown --recursive debian-tor:debian-tor /var/log/$NAME.log
 # Function that starts the daemon/service
 #
 do_start()
-{
+   {
    # Return
    #   0 if daemon has been started
    #   1 if daemon was already running
@@ -59,43 +60,46 @@ do_start()
 
    source /usr/lib/anon-shared-helper-scripts/torsocks-remove-ld-preload
 
-   start-stop-daemon \
-      --start \
-      --quiet \
-      --background \
-      --make-pidfile \
-      --pidfile $PIDFILE \
-      --chuid debian-tor:debian-tor \
-      --exec "$DAEMON" -- \
-      $DAEMON_ARGS \
-         || return 2
-
-   # Add code here, if necessary, that waits for the process to be ready
-   # to handle requests from services started subsequently which depend
-   # on this one.  As a last resort, sleep for some time.
-}
-
+   cpfpd start
 #
-# Function that stops the daemon/service
+#    start-stop-daemon \
+#       --start \
+#       --quiet \
+#       --background \
+#       --make-pidfile \
+#       --pidfile $PIDFILE \
+#       --chuid debian-tor:debian-tor \
+#       --exec "$DAEMON" -- \
+#       $DAEMON_ARGS \
+#          || return 2
 #
-do_stop()
-{
-   # Return
-   #   0 if daemon has been stopped
-   #   1 if daemon was already stopped
-   #   2 if daemon could not be stopped
-   #   other if a failure occurred
-
-   /sbin/start-stop-daemon \
-      --stop \
-      --quiet \
-      --pidfile "$PIDFILE" \
-      --signal TERM \
-      --retry 5
-
-   rm -f "$PIDFILE"
-   return 0
+#    # Add code here, if necessary, that waits for the process to be ready
+#    # to handle requests from services started subsequently which depend
+#    # on this one.  As a last resort, sleep for some time.
 }
+#
+# #
+# # Function that stops the daemon/service
+# #
+ do_stop()
+   {
+   cpfpd stop
+#    # Return
+#    #   0 if daemon has been stopped
+#    #   1 if daemon was already stopped
+#    #   2 if daemon could not be stopped
+#    #   other if a failure occurred
+#
+#    /sbin/start-stop-daemon \
+#       --stop \
+#       --quiet \
+#       --pidfile "$PIDFILE" \
+#       --signal TERM \
+#       --retry 5
+#
+#    rm -f "$PIDFILE"
+#    return 0
+ }
 
 case "$1" in
   start)
@@ -106,15 +110,17 @@ case "$1" in
 		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
 		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
 	esac
-	;;
+ 	;;
   stop)
+
 	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
-	do_stop
+        ## generates an error (pid file not existing).
+	#do_stop
 	case "$?" in
 		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
 		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
 	esac
-	;;
+ 	;;
   status)
 	status_of_proc -p "$PIDFILE" "$DAEMON" "$NAME" && exit 0 || exit $?
 	;;
@@ -148,7 +154,7 @@ case "$1" in
 		log_end_msg 1
 		;;
 	esac
-	;;
+ 	;;
   *)
 	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
 	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
