Commented out bash source for /etc/controlportfilt.d/

diff --git a/usr/bin/controlportfilt b/usr/bin/controlportfilt
--- a/usr/bin/controlportfilt
+++ b/usr/bin/controlportfilt
@@ -60,6 +60,30 @@ trap_sigterm() {
 
 trap "trap_sigterm" SIGTERM
 
+#if [ -d /etc/controlportfilt.d ]; then
+#   for i in /etc/controlportfilt.d/*; do
+#      if [ -f "$i" ]; then
+#         ## If the last character is a ~, ignore that file,
+#         ## because it was created by some editor,
+#         ## which creates backup files.
+#         if [ "${i: -1}" = "~" ]; then
+#            continue
+#         fi
+#         ## Skipping files such as .dpkg-old and .dpkg-dist.
+#         if ( echo "$i" | grep -q ".dpkg-" ); then
+#            true "skip $i"
+#            continue
+#         fi
+#         bash -n "$i"
+#         source "$i"
+#      fi
+#   done
+#else
+#   echo "$ID ERROR: configuration folder /etc/controlportfilt.d does not exist."
+#   exit 1
+#fi
+
+
 /usr/lib/cpfp.py &
 #tcpserver \
 #   -v \
